/**
 * 统一错误码定义
 *
 * 错误码规范：
 * - 0: 成功
 * - 1-99: 通用错误
 * - 1xxx: 认证模块
 * - 2xxx: 玩家/角色模块
 * - 3xxx: 修炼模块
 * - 4xxx: 宗门模块
 * - 5xxx: 战斗模块
 * - 6xxx: 物品/背包模块
 * - 7xxx: 药园模块（黄枫谷）
 * - 8xxx: 太一门模块
 * - 9xxx: 星宫模块
 * - 10xxx: 黑煞教模块
 * - 11xxx: PvP模块
 * - 12xxx: 万灵宗模块
 * - 13xxx: 落云宗模块
 * - 14xxx: 元婴宗模块
 * - 15xxx: 夺宝模块
 * - 16xxx: 试炼古塔模块
 * - 17xxx: 万宝楼模块
 */

export const ERROR_CODES = {
  // ============ 成功 ============
  SUCCESS: 0,

  // ============ 通用错误 (1-99) ============
  UNKNOWN_ERROR: 1,
  VALIDATION_ERROR: 2,
  NOT_FOUND: 3,
  FORBIDDEN: 4,
  INTERNAL_ERROR: 5,

  // ============ 认证模块 (1xxx) ============
  AUTH_TOKEN_MISSING: 1001,
  AUTH_TOKEN_INVALID: 1002,
  AUTH_TOKEN_EXPIRED: 1003,
  AUTH_INVALID_CREDENTIALS: 1004,
  AUTH_USER_NOT_FOUND: 1005,
  AUTH_USER_ALREADY_EXISTS: 1006,
  AUTH_REFRESH_TOKEN_INVALID: 1007,
  AUTH_ACCOUNT_DELETED: 1008,

  // ============ 玩家/角色模块 (2xxx) ============
  PLAYER_NOT_AUTHENTICATED: 2001,
  PLAYER_CHARACTER_NOT_FOUND: 2002,
  PLAYER_CHARACTER_EXISTS: 2003,
  PLAYER_INVALID_NAME: 2004,
  PLAYER_SPIRIT_ROOT_INVALID: 2005,
  PLAYER_NOT_ENOUGH_SPIRIT_STONES: 2006,

  // ============ 修炼模块 (3xxx) ============
  CULTIVATION_NO_CHARACTER: 3001,
  CULTIVATION_COOLDOWN: 3002,
  CULTIVATION_ALREADY_IN_PROGRESS: 3003,
  CULTIVATION_DEEP_NOT_ACTIVE: 3004,
  CULTIVATION_DEEP_NOT_FINISHED: 3005,
  CULTIVATION_PEACE_MODE_UNAVAILABLE: 3006,
  CULTIVATION_POISON_CLEAR_FAILED: 3007,
  CULTIVATION_BREAKTHROUGH_FAILED: 3008,

  // ============ 宗门模块 (4xxx) ============
  SECT_NOT_MEMBER: 4001,
  SECT_ALREADY_MEMBER: 4002,
  SECT_NOT_FOUND: 4003,
  SECT_REQUIREMENTS_NOT_MET: 4004,
  SECT_LEAVE_COOLDOWN: 4005,
  SECT_SALARY_ALREADY_CLAIMED: 4006,
  SECT_CHECKIN_ALREADY_DONE: 4007,
  SECT_TEACH_LIMIT_REACHED: 4008,
  SECT_PROMOTE_REQUIREMENTS_NOT_MET: 4009,
  SECT_CONTRIBUTION_NOT_ENOUGH: 4010,
  SECT_ITEM_NOT_FOUND: 4011,
  SECT_BOUNTY_NOT_FOUND: 4012,
  SECT_BOUNTY_ALREADY_ACCEPTED: 4013,
  SECT_BOUNTY_NOT_ACTIVE: 4014,
  SECT_DONATE_INVALID_AMOUNT: 4015,

  // ============ 战斗模块 (5xxx) ============
  BATTLE_NOT_AVAILABLE: 5001,
  BATTLE_TARGET_NOT_FOUND: 5002,
  BATTLE_IN_PEACE_MODE: 5003,
  BATTLE_FORMATION_ALREADY_ACTIVE: 5004, // 阵法已激活
  BATTLE_FORMATION_REQUIREMENTS: 5005, // 阵法要求未满足
  BATTLE_NOT_ENOUGH_RESOURCES: 5006, // 资源不足
  BATTLE_FORMATION_NOT_LEARNED: 5007, // 阵法未学习
  BATTLE_FORMATION_EXPIRED: 5008, // 阵法已过期
  BATTLE_DUMMY_COOLDOWN: 5009, // 木人桩冷却中
  BATTLE_DUMMY_REALM_TOO_HIGH: 5010, // 木人桩境界过高

  // ============ 物品/背包模块 (6xxx) ============
  ITEM_NOT_FOUND: 6001,
  ITEM_NOT_ENOUGH: 6002,
  INVENTORY_FULL: 6003,
  ITEM_NOT_USABLE: 6004,
  ITEM_USE_CONDITION_NOT_MET: 6005,
  ITEM_NOT_TRADEABLE: 6006,
  ITEM_ALREADY_BOUND: 6007,
  RECIPE_NOT_LEARNED: 6008,
  RECIPE_ALREADY_LEARNED: 6009,
  RECIPE_MATERIALS_NOT_ENOUGH: 6010,
  RECIPE_REQUIREMENTS_NOT_MET: 6011,
  CRAFT_FAILED: 6012,
  GIFT_TARGET_NOT_FOUND: 6013,
  GIFT_SELF_NOT_ALLOWED: 6014,
  GIFT_TARGET_INVENTORY_FULL: 6015,

  // ============ 药园模块 (7xxx) ============
  GARDEN_NOT_HUANG_FENG: 7001, // 非黄枫谷弟子
  GARDEN_PLOT_NOT_FOUND: 7002, // 地块不存在
  GARDEN_PLOT_NOT_EMPTY: 7003, // 地块非空
  GARDEN_PLOT_NOT_MATURE: 7004, // 地块未成熟
  GARDEN_PLOT_LOCKED: 7005, // 地块未解锁
  GARDEN_SEED_NOT_FOUND: 7006, // 种子不存在
  GARDEN_SEED_NOT_ENOUGH: 7007, // 种子不足
  GARDEN_NO_EVENT: 7008, // 无事件需处理
  GARDEN_MAX_PLOTS: 7009, // 已达最大灵田数
  GARDEN_NOT_ELDER: 7010, // 非丹道长老
  GARDEN_ELDER_REQUIREMENT: 7011, // 不满足长老条件
  GARDEN_NOT_GRAND_ELDER: 7012, // 非太上长老（洞天寻宝）
  GARDEN_EXPLORE_LIMIT: 7013, // 探索次数已达上限
  GARDEN_SEED_NOT_MATCH_PLOT: 7014, // 种子与地块类型不匹配
  GARDEN_PLOT_WITHERED: 7015, // 地块已枯萎
  GARDEN_IN_COMBAT: 7016, // 正在战斗中
  GARDEN_NOT_IN_COMBAT: 7017, // 不在战斗中
  GARDEN_PLOT_HAS_EVENT: 7018, // 地块有未处理事件

  // ============ 太一门模块 (8xxx) ============
  TAIYI_NOT_MEMBER: 8001, // 非太一门弟子
  TAIYI_GUIDANCE_COOLDOWN: 8002, // 引道冷却中
  TAIYI_INVALID_ELEMENT: 8003, // 无效的元素类型
  TAIYI_CONSCIOUSNESS_NOT_ENOUGH: 8004, // 神识不足
  TAIYI_STRIKE_TARGET_NOT_FOUND: 8005, // 神识冲击目标不存在
  TAIYI_STRIKE_SELF_NOT_ALLOWED: 8006, // 不能对自己使用神识冲击
  TAIYI_STRIKE_FAILED: 8007, // 神识冲击失败
  TAIYI_BUFF_NOT_ACTIVE: 8008, // 没有激活的引道增益

  // ============ 星宫模块 (9xxx) ============
  STAR_NOT_STAR_PALACE: 9001, // 非星宫弟子
  STAR_CONSORT_NOT_FOUND: 9002, // 侍妾不存在
  STAR_GREETING_COOLDOWN: 9003, // 问安冷却中
  STAR_GIFT_NOT_ENOUGH: 9004, // 赠礼资源不足
  STAR_DISK_NOT_FOUND: 9005, // 引星盘不存在
  STAR_DISK_NOT_IDLE: 9006, // 引星盘非空闲
  STAR_DISK_NOT_READY: 9007, // 引星盘未完成
  STAR_DISK_LOCKED: 9008, // 引星盘未解锁
  STAR_DISK_NO_EVENT: 9009, // 无事件需处理
  STAR_DISK_MAX: 9010, // 已达最大引星盘数
  STAR_ARRAY_COOLDOWN: 9011, // 大阵冷却中
  STAR_ARRAY_NOT_FOUND: 9012, // 大阵不存在
  STAR_ARRAY_ALREADY_JOINED: 9013, // 已加入大阵
  STAR_ARRAY_FULL: 9014, // 大阵人数已满
  STAR_ARRAY_REALM_NOT_MET: 9015, // 境界不足
  STAR_GAZE_COOLDOWN: 9016, // 观星冷却中
  STAR_CHANGE_FATE_COOLDOWN: 9017, // 改命冷却中
  STAR_CONSORT_ASSIGNED: 9018, // 侍妾已派遣
  STAR_SPIRIT_FEEDBACK_ACTIVE: 9019, // 灵力反哺生效中
  STAR_DISK_HAS_EVENT: 9020, // 引星盘有未处理事件
  STAR_INVALID_STAR_TYPE: 9021, // 无效的星辰类型
  STAR_ARRAY_EXPIRED: 9022, // 大阵已过期
  STAR_CONSORT_NOT_ASSIGNED: 9023, // 侍妾未派遣
  STAR_CONSORT_STOLEN: 9024, // 侍妾已被黑煞教窃取

  // ============ 黑煞教模块 (10xxx) ============
  HEISHA_NOT_MEMBER: 10001, // 非黑煞教弟子
  HEISHA_SEIZE_COOLDOWN: 10002, // 夺舍冷却中
  HEISHA_SEIZE_REALM_LOW: 10003, // 境界不足
  HEISHA_SEIZE_TARGET_HIGHER: 10004, // 目标境界过高
  HEISHA_SEIZE_TARGET_SELF: 10005, // 不能对自己使用
  HEISHA_SEIZE_TARGET_SAME_SECT: 10006, // 不能对同门使用
  HEISHA_SEIZE_MAX_PUPPETS: 10007, // 傀儡数量已满
  HEISHA_SEIZE_ALREADY_ENSLAVED: 10008, // 目标已被奴役
  HEISHA_SEIZE_FAILED: 10009, // 夺舍失败（反噬）
  HEISHA_THEFT_COOLDOWN: 10010, // 窃取冷却中
  HEISHA_THEFT_REALM_LOW: 10011, // 窃取境界不足
  HEISHA_THEFT_TARGET_NO_CONSORT: 10012, // 目标无侍妾
  HEISHA_THEFT_TARGET_NOT_STAR: 10013, // 目标非星宫弟子
  HEISHA_THEFT_ALREADY_STOLEN: 10014, // 侍妾已被窃取
  HEISHA_BRAINWASH_LIMIT: 10015, // 魔音灌脑次数用尽
  HEISHA_EXTRACT_LIMIT: 10016, // 强索元阴次数用尽
  HEISHA_NO_STOLEN_CONSORT: 10017, // 无被窃取的侍妾
  HEISHA_PUPPET_NOT_FOUND: 10018, // 傀儡不存在
  HEISHA_ENSLAVED: 10019, // 你正被奴役，无法执行此操作
  HEISHA_CULTIVATION_BLOCKED: 10020, // 修炼功能被封锁
  HEISHA_TARGET_NOT_FOUND: 10021, // 目标不存在

  // 血魂幡系统 (10050-10099)
  HEISHA_BANNER_NOT_UNLOCKED: 10050, // 尚未获得血魂幡
  HEISHA_BANNER_MAX_LEVEL: 10051, // 血魂幡已达最高等阶
  HEISHA_SACRIFICE_COOLDOWN: 10052, // 每日献祭冷却中
  HEISHA_CONVERT_LIMIT: 10053, // 化功为煞每日次数用尽
  HEISHA_BANNER_LEVEL_LOW: 10054, // 血魂幡等阶不足
  HEISHA_SLOT_NOT_EMPTY: 10055, // 炼化槽正在使用中
  HEISHA_SOUL_NOT_ENOUGH: 10056, // 魂魄数量不足
  HEISHA_SHA_NOT_ENOUGH: 10057, // 煞气不足
  HEISHA_SLOT_NOT_REFINING: 10058, // 槽位未在炼化中
  HEISHA_SLOT_NOT_COMPLETE: 10059, // 炼化尚未完成
  HEISHA_FOREST_LIMIT: 10060, // 血洗山林次数用尽
  HEISHA_SHADOW_LIMIT: 10061, // 召唤魔影次数用尽

  // 丹魔之咒错误码 (10100-10199)
  CURSE_SELF_TARGET: 10100, // 不能对自己施咒
  CURSE_NO_ITEM: 10101, // 缺少丹魔心萃
  CURSE_NOT_ENOUGH_CULTIVATION: 10102, // 修为不足
  CURSE_TARGET_NOT_FOUND: 10103, // 目标不存在
  CURSE_TARGET_ALREADY_CURSED: 10104, // 目标已被下咒
  CURSE_NOT_CASTER: 10105, // 不是施咒者
  CURSE_EXPIRED: 10106, // 咒印已过期
  CURSE_NOT_CURSED: 10107, // 未被下咒
  CURSE_NO_ANTIDOTE: 10108, // 缺少解咒丹药

  // ============ PvP模块 (11xxx) ============
  PVP_LIMIT_REACHED: 11001, // PvP次数用尽
  PVP_TARGET_SELF: 11002, // 不能挑战自己
  PVP_TARGET_NOT_FOUND: 11003, // 目标不存在
  PVP_TARGET_SAME_SECT: 11004, // 不能挑战同门
  PVP_REALM_TOO_LOW: 11005, // 境界不足
  PVP_TARGET_PEACE_MODE: 11006, // 目标处于和平模式
  PVP_SOUL_SHATTERED: 11007, // 道心破碎，无法主动发起斗法

  // ============ 夺宝模块 (15xxx) ============
  LOOT_TARGET_SELF: 15001, // 不能掠夺自己
  LOOT_TARGET_NOT_FOUND: 15002, // 目标不存在
  LOOT_TARGET_PEACE_MODE: 15003, // 目标处于和平模式
  LOOT_TARGET_NOT_ENOUGH_STONES: 15004, // 目标灵石不足
  LOOT_COOLDOWN: 15005, // 冷却中
  LOOT_DAILY_LIMIT: 15006, // 每日次数用尽
  LOOT_REALM_TOO_LOW: 15007, // 境界不足

  // ============ 万灵宗模块 (12xxx) ============
  WANLING_NOT_MEMBER: 12001, // 非万灵宗弟子
  WANLING_BEAST_NOT_FOUND: 12002, // 灵兽不存在
  WANLING_BEAST_MAX_CAPACITY: 12003, // 灵兽数量已满
  WANLING_SEARCH_COOLDOWN: 12004, // 寻觅冷却中
  WANLING_SEARCH_DAILY_LIMIT: 12005, // 每日寻觅次数已用尽
  WANLING_SEARCH_FAILED: 12006, // 寻觅失败
  WANLING_FEED_NO_FOOD: 12007, // 没有食物
  WANLING_FEED_SATIETY_FULL: 12008, // 饱食度已满
  WANLING_BEAST_NOT_OWNED: 12009, // 该灵兽不属于你
  WANLING_BEAST_ALREADY_DEPLOYED: 12010, // 灵兽已出战
  WANLING_BEAST_NOT_DEPLOYED: 12011, // 灵兽未出战
  WANLING_BEAST_INJURED: 12012, // 灵兽受伤中
  WANLING_BEAST_BUSY: 12013, // 灵兽正在执行任务
  WANLING_RAID_COOLDOWN: 12014, // 偷菜冷却中
  WANLING_RAID_DAILY_LIMIT: 12015, // 每日偷菜次数已用尽
  WANLING_RAID_NO_DEPLOYED: 12016, // 没有出战的灵兽
  WANLING_RAID_TARGET_NOT_FOUND: 12017, // 偷菜目标不存在
  WANLING_RAID_TARGET_NO_GARDEN: 12018, // 目标没有药园
  WANLING_RAID_REALM_LOW: 12019, // 境界不足
  WANLING_EVOLVE_LEVEL_NOT_MET: 12020, // 进化等级不足
  WANLING_EVOLVE_ITEMS_NOT_ENOUGH: 12021, // 进化材料不足
  WANLING_EVOLVE_NOT_AVAILABLE: 12022, // 该灵兽无法进化
  WANLING_NAME_INVALID: 12023, // 灵兽名字无效
  WANLING_NAME_TOO_LONG: 12024, // 灵兽名字过长
  WANLING_MAX_DEPLOYED: 12025, // 出战灵兽数量已满
  WANLING_ABYSS_REALM_LOW: 12026, // 探渊境界不足
  WANLING_ABYSS_COOLDOWN: 12027, // 探渊冷却中

  // ============ 落云宗模块 (13xxx) ============
  LUOYUN_NOT_MEMBER: 13001, // 非落云宗弟子
  LUOYUN_WATERING_DAILY_LIMIT: 13002, // 今日已浇灌
  LUOYUN_WATERING_EXP_NOT_ENOUGH: 13003, // 修为不足
  LUOYUN_PILL_NOT_FOUND: 13004, // 妖丹不存在
  LUOYUN_PILL_NOT_ENOUGH: 13005, // 妖丹数量不足
  LUOYUN_TREE_NOT_HARVESTING: 13006, // 灵树未到收获期
  LUOYUN_TREE_INVADED: 13007, // 灵树正被入侵
  LUOYUN_ALREADY_DEFENDED: 13008, // 已参与防御
  LUOYUN_NOT_IN_INVASION: 13009, // 当前无入侵事件
  LUOYUN_REWARDS_CLAIMED: 13010, // 奖励已领取
  LUOYUN_NO_CONTRIBUTION: 13011, // 无贡献无法领取
  LUOYUN_ROOT_ALREADY_UPGRADED: 13012, // 灵根已用灵眼之液升级
  LUOYUN_LIQUID_NOT_ENOUGH: 13013, // 灵眼之液不足
  LUOYUN_INVASION_FAILED: 13014, // 防御失败
  LUOYUN_INVALID_PILL_TIER: 13015, // 无效的妖丹等级
  LUOYUN_TREE_NOT_GROWING: 13016, // 灵树非生长期
  LUOYUN_ENVIRONMENT_SATISFIED: 13017, // 环境已被满足
  LUOYUN_CANNOT_SATISFY_ENVIRONMENT: 13018, // 灵根无法满足当前环境

  // ============ 元婴宗模块 (14xxx) ============
  YUANYING_NOT_MEMBER: 14001, // 非元婴宗弟子
  YUANYING_REALM_TOO_LOW: 14002, // 境界不足（需元婴期）
  YUANYING_SOUL_BUSY: 14003, // 元婴正在活动中
  YUANYING_SOUL_IDLE: 14004, // 元婴处于静养状态
  YUANYING_PROJECTION_NOT_COMPLETE: 14005, // 出窍尚未完成
  YUANYING_CULTIVATION_NOT_AVAILABLE: 14006, // 元婴闭关不可用
  YUANYING_SEEK_TRUTH_COOLDOWN: 14007, // 问道寻真冷却中
  YUANYING_SEEK_TRUTH_EXP_NOT_ENOUGH: 14008, // 修为不足
  YUANYING_FRAGMENT_INCOMPLETE: 14009, // 残篇未集齐
  YUANYING_SWORD_ALREADY_MASTERED: 14010, // 青元剑诀已领悟
  YUANYING_MASTER_EXP_NOT_ENOUGH: 14011, // 领悟修为不足
  YUANYING_NO_NASCENT_SOUL: 14012, // 尚未凝聚元婴

  // ============ 试炼古塔模块 (16xxx) ============
  TOWER_NO_ATTEMPTS: 16001, // 今日挑战次数已用尽
  TOWER_NOT_IN_TOWER: 16002, // 未进入古塔
  TOWER_MAX_FLOOR: 16003, // 已到达最高层
  TOWER_FREE_ATTEMPTS_LEFT: 16004, // 还有免费次数
  TOWER_MAX_RESETS: 16005, // 今日重置次数已达上限
  TOWER_NOT_ENOUGH_EXP: 16006, // 修为不足
  TOWER_IN_TOWER: 16007, // 正在塔中，无法操作

  // ============ 万宝楼模块 (17xxx) ============
  MARKET_LISTING_NOT_FOUND: 17001, // 挂单不存在
  MARKET_ITEM_NOT_TRADEABLE: 17002, // 物品不可交易
  MARKET_ITEM_IS_BOUND: 17003, // 物品已绑定
  MARKET_NOT_ENOUGH_ITEMS: 17004, // 物品数量不足
  MARKET_NOT_ENOUGH_PAYMENT: 17005, // 支付物品不足
  MARKET_CANNOT_BUY_OWN: 17006, // 不能购买自己的物品
  MARKET_LISTING_SOLD_OUT: 17007, // 已售罄
  MARKET_INVALID_QUANTITY: 17008, // 购买数量无效
  MARKET_INVALID_PRICE: 17009, // 价格配置无效
  MARKET_BUYER_INVENTORY_FULL: 17010, // 买家储物袋已满
  MARKET_SELLER_INVENTORY_FULL: 17011, // 卖家储物袋已满
  MARKET_NOT_LISTING_OWNER: 17012, // 不是挂单所有者
  MARKET_LISTING_CANCELLED: 17013, // 挂单已取消
  MARKET_BUNDLE_MUST_BUY_ALL: 17014, // 捆绑销售必须全部购买

  // ============ 洞府模块 (18xxx) ============
  CAVE_NOT_OPENED: 18001, // 尚未开辟洞府
  CAVE_ALREADY_OPENED: 18002, // 已拥有洞府
  CAVE_REALM_NOT_MET: 18003, // 境界不足
  CAVE_RESOURCES_NOT_ENOUGH: 18004, // 资源不足
  CAVE_SPIRIT_VEIN_MAX: 18005, // 灵脉已满级
  CAVE_MEDITATION_MAX: 18006, // 静室已满级
  CAVE_NO_PENDING_ENERGY: 18007, // 无待收取灵气
  CAVE_NO_PENDING_EXP: 18008, // 无待转化修为
  CAVE_TREASURE_SLOT_INVALID: 18009, // 展台槽位无效
  CAVE_TREASURE_ALREADY_DISPLAYED: 18010, // 物品已在展示
  CAVE_TREASURE_SLOT_EMPTY: 18011, // 展台无物品
  CAVE_SCENERY_NOT_UNLOCKED: 18012, // 景观未解锁
  CAVE_NO_VISITOR: 18013, // 当前无访客
  CAVE_VISITOR_EXPIRED: 18014, // 访客已离开
  CAVE_TARGET_NO_CAVE: 18015, // 目标未开辟洞府
  CAVE_VISIT_SELF: 18016, // 不能拜访自己
  CAVE_MESSAGE_EMPTY: 18017, // 留言内容为空
  CAVE_MESSAGE_TOO_LONG: 18018, // 留言内容过长
  CAVE_MESSAGE_NOT_FOUND: 18019, // 留言不存在

  // ============ 副本模块 (19xxx) ============
  DUNGEON_ALREADY_IN_ROOM: 19001, // 已在房间中
  DUNGEON_NOT_IN_ROOM: 19002, // 不在房间中
  DUNGEON_ROOM_NOT_FOUND: 19003, // 房间不存在
  DUNGEON_ROOM_FULL: 19004, // 房间已满
  DUNGEON_NOT_LEADER: 19005, // 不是队长
  DUNGEON_NOT_ENOUGH_PLAYERS: 19006, // 人数不足
  DUNGEON_REALM_NOT_MET: 19007, // 境界不足
  DUNGEON_NO_ENTRY_ITEM: 19008, // 缺少入场物品
  DUNGEON_ALREADY_STARTED: 19009, // 副本已开始
  DUNGEON_NOT_STARTED: 19010, // 副本未开始
  DUNGEON_INVALID_PATH: 19011, // 无效的路径选择
  DUNGEON_PATH_ALREADY_SELECTED: 19012, // 路径已选择
  DUNGEON_STAGE_NOT_READY: 19013, // 关卡未准备好
  DUNGEON_COMPLETED: 19014, // 副本已完成
  DUNGEON_FAILED: 19015, // 副本已失败

  // ============ 宗门外交模块 (20xxx) ============
  DIPLOMACY_NOT_MASTER: 20001, // 非掌门，无权操作
  DIPLOMACY_COOLDOWN: 20002, // 24小时冷却中
  DIPLOMACY_SAME_SECT: 20003, // 不能对自己宗门操作
  DIPLOMACY_TARGET_NOT_FRIENDLY: 20004, // 目标未友好，无法结盟
  DIPLOMACY_PROPOSAL_EXPIRED: 20005, // 结盟请求已过期
  DIPLOMACY_ALLIANCE_PENALTY: 20006, // 背盟惩罚期间，无法结盟
  DIPLOMACY_NO_RELATION: 20007, // 无此关系可解除
  DIPLOMACY_SELF_RELATION: 20008, // 不能改变与自己宗门的关系
  DIPLOMACY_NOT_IN_SECT: 20009, // 未加入宗门
  DIPLOMACY_TARGET_SECT_NOT_FOUND: 20010, // 目标宗门不存在
  DIPLOMACY_ALREADY_ALLIED: 20011, // 已经是盟友
  DIPLOMACY_NO_PENDING_REQUEST: 20012 // 无待处理的结盟请求
} as const

export type ErrorCode = (typeof ERROR_CODES)[keyof typeof ERROR_CODES]

// 错误类型映射（数字码 -> 字符串类型）
export const ERROR_TYPES: Record<number, string> = {
  [ERROR_CODES.SUCCESS]: 'SUCCESS',
  [ERROR_CODES.UNKNOWN_ERROR]: 'UNKNOWN_ERROR',
  [ERROR_CODES.VALIDATION_ERROR]: 'VALIDATION_ERROR',
  [ERROR_CODES.NOT_FOUND]: 'NOT_FOUND',
  [ERROR_CODES.FORBIDDEN]: 'FORBIDDEN',
  [ERROR_CODES.INTERNAL_ERROR]: 'INTERNAL_ERROR',

  [ERROR_CODES.AUTH_TOKEN_MISSING]: 'AUTH_TOKEN_MISSING',
  [ERROR_CODES.AUTH_TOKEN_INVALID]: 'AUTH_TOKEN_INVALID',
  [ERROR_CODES.AUTH_TOKEN_EXPIRED]: 'AUTH_TOKEN_EXPIRED',
  [ERROR_CODES.AUTH_INVALID_CREDENTIALS]: 'AUTH_INVALID_CREDENTIALS',
  [ERROR_CODES.AUTH_USER_NOT_FOUND]: 'AUTH_USER_NOT_FOUND',
  [ERROR_CODES.AUTH_USER_ALREADY_EXISTS]: 'AUTH_USER_ALREADY_EXISTS',
  [ERROR_CODES.AUTH_REFRESH_TOKEN_INVALID]: 'AUTH_REFRESH_TOKEN_INVALID',
  [ERROR_CODES.AUTH_ACCOUNT_DELETED]: 'AUTH_ACCOUNT_DELETED',

  [ERROR_CODES.PLAYER_NOT_AUTHENTICATED]: 'PLAYER_NOT_AUTHENTICATED',
  [ERROR_CODES.PLAYER_CHARACTER_NOT_FOUND]: 'PLAYER_CHARACTER_NOT_FOUND',
  [ERROR_CODES.PLAYER_CHARACTER_EXISTS]: 'PLAYER_CHARACTER_EXISTS',
  [ERROR_CODES.PLAYER_INVALID_NAME]: 'PLAYER_INVALID_NAME',
  [ERROR_CODES.PLAYER_SPIRIT_ROOT_INVALID]: 'PLAYER_SPIRIT_ROOT_INVALID',
  [ERROR_CODES.PLAYER_NOT_ENOUGH_SPIRIT_STONES]: 'PLAYER_NOT_ENOUGH_SPIRIT_STONES',

  [ERROR_CODES.CULTIVATION_NO_CHARACTER]: 'CULTIVATION_NO_CHARACTER',
  [ERROR_CODES.CULTIVATION_COOLDOWN]: 'CULTIVATION_COOLDOWN',
  [ERROR_CODES.CULTIVATION_ALREADY_IN_PROGRESS]: 'CULTIVATION_ALREADY_IN_PROGRESS',
  [ERROR_CODES.CULTIVATION_DEEP_NOT_ACTIVE]: 'CULTIVATION_DEEP_NOT_ACTIVE',
  [ERROR_CODES.CULTIVATION_DEEP_NOT_FINISHED]: 'CULTIVATION_DEEP_NOT_FINISHED',
  [ERROR_CODES.CULTIVATION_PEACE_MODE_UNAVAILABLE]: 'CULTIVATION_PEACE_MODE_UNAVAILABLE',
  [ERROR_CODES.CULTIVATION_POISON_CLEAR_FAILED]: 'CULTIVATION_POISON_CLEAR_FAILED',
  [ERROR_CODES.CULTIVATION_BREAKTHROUGH_FAILED]: 'CULTIVATION_BREAKTHROUGH_FAILED',

  [ERROR_CODES.SECT_NOT_MEMBER]: 'SECT_NOT_MEMBER',
  [ERROR_CODES.SECT_ALREADY_MEMBER]: 'SECT_ALREADY_MEMBER',
  [ERROR_CODES.SECT_NOT_FOUND]: 'SECT_NOT_FOUND',
  [ERROR_CODES.SECT_REQUIREMENTS_NOT_MET]: 'SECT_REQUIREMENTS_NOT_MET',
  [ERROR_CODES.SECT_LEAVE_COOLDOWN]: 'SECT_LEAVE_COOLDOWN',
  [ERROR_CODES.SECT_SALARY_ALREADY_CLAIMED]: 'SECT_SALARY_ALREADY_CLAIMED',
  [ERROR_CODES.SECT_CHECKIN_ALREADY_DONE]: 'SECT_CHECKIN_ALREADY_DONE',
  [ERROR_CODES.SECT_TEACH_LIMIT_REACHED]: 'SECT_TEACH_LIMIT_REACHED',
  [ERROR_CODES.SECT_PROMOTE_REQUIREMENTS_NOT_MET]: 'SECT_PROMOTE_REQUIREMENTS_NOT_MET',
  [ERROR_CODES.SECT_CONTRIBUTION_NOT_ENOUGH]: 'SECT_CONTRIBUTION_NOT_ENOUGH',
  [ERROR_CODES.SECT_ITEM_NOT_FOUND]: 'SECT_ITEM_NOT_FOUND',
  [ERROR_CODES.SECT_BOUNTY_NOT_FOUND]: 'SECT_BOUNTY_NOT_FOUND',
  [ERROR_CODES.SECT_BOUNTY_ALREADY_ACCEPTED]: 'SECT_BOUNTY_ALREADY_ACCEPTED',
  [ERROR_CODES.SECT_BOUNTY_NOT_ACTIVE]: 'SECT_BOUNTY_NOT_ACTIVE',
  [ERROR_CODES.SECT_DONATE_INVALID_AMOUNT]: 'SECT_DONATE_INVALID_AMOUNT',

  [ERROR_CODES.BATTLE_NOT_AVAILABLE]: 'BATTLE_NOT_AVAILABLE',
  [ERROR_CODES.BATTLE_TARGET_NOT_FOUND]: 'BATTLE_TARGET_NOT_FOUND',
  [ERROR_CODES.BATTLE_IN_PEACE_MODE]: 'BATTLE_IN_PEACE_MODE',
  [ERROR_CODES.BATTLE_FORMATION_ALREADY_ACTIVE]: 'BATTLE_FORMATION_ALREADY_ACTIVE',
  [ERROR_CODES.BATTLE_FORMATION_REQUIREMENTS]: 'BATTLE_FORMATION_REQUIREMENTS',
  [ERROR_CODES.BATTLE_NOT_ENOUGH_RESOURCES]: 'BATTLE_NOT_ENOUGH_RESOURCES',
  [ERROR_CODES.BATTLE_FORMATION_NOT_LEARNED]: 'BATTLE_FORMATION_NOT_LEARNED',
  [ERROR_CODES.BATTLE_FORMATION_EXPIRED]: 'BATTLE_FORMATION_EXPIRED',
  [ERROR_CODES.BATTLE_DUMMY_COOLDOWN]: 'BATTLE_DUMMY_COOLDOWN',
  [ERROR_CODES.BATTLE_DUMMY_REALM_TOO_HIGH]: 'BATTLE_DUMMY_REALM_TOO_HIGH',

  [ERROR_CODES.ITEM_NOT_FOUND]: 'ITEM_NOT_FOUND',
  [ERROR_CODES.ITEM_NOT_ENOUGH]: 'ITEM_NOT_ENOUGH',
  [ERROR_CODES.INVENTORY_FULL]: 'INVENTORY_FULL',
  [ERROR_CODES.ITEM_NOT_USABLE]: 'ITEM_NOT_USABLE',
  [ERROR_CODES.ITEM_USE_CONDITION_NOT_MET]: 'ITEM_USE_CONDITION_NOT_MET',
  [ERROR_CODES.ITEM_NOT_TRADEABLE]: 'ITEM_NOT_TRADEABLE',
  [ERROR_CODES.ITEM_ALREADY_BOUND]: 'ITEM_ALREADY_BOUND',
  [ERROR_CODES.RECIPE_NOT_LEARNED]: 'RECIPE_NOT_LEARNED',
  [ERROR_CODES.RECIPE_ALREADY_LEARNED]: 'RECIPE_ALREADY_LEARNED',
  [ERROR_CODES.RECIPE_MATERIALS_NOT_ENOUGH]: 'RECIPE_MATERIALS_NOT_ENOUGH',
  [ERROR_CODES.RECIPE_REQUIREMENTS_NOT_MET]: 'RECIPE_REQUIREMENTS_NOT_MET',
  [ERROR_CODES.CRAFT_FAILED]: 'CRAFT_FAILED',
  [ERROR_CODES.GIFT_TARGET_NOT_FOUND]: 'GIFT_TARGET_NOT_FOUND',
  [ERROR_CODES.GIFT_SELF_NOT_ALLOWED]: 'GIFT_SELF_NOT_ALLOWED',
  [ERROR_CODES.GIFT_TARGET_INVENTORY_FULL]: 'GIFT_TARGET_INVENTORY_FULL',

  [ERROR_CODES.GARDEN_NOT_HUANG_FENG]: 'GARDEN_NOT_HUANG_FENG',
  [ERROR_CODES.GARDEN_PLOT_NOT_FOUND]: 'GARDEN_PLOT_NOT_FOUND',
  [ERROR_CODES.GARDEN_PLOT_NOT_EMPTY]: 'GARDEN_PLOT_NOT_EMPTY',
  [ERROR_CODES.GARDEN_PLOT_NOT_MATURE]: 'GARDEN_PLOT_NOT_MATURE',
  [ERROR_CODES.GARDEN_PLOT_LOCKED]: 'GARDEN_PLOT_LOCKED',
  [ERROR_CODES.GARDEN_SEED_NOT_FOUND]: 'GARDEN_SEED_NOT_FOUND',
  [ERROR_CODES.GARDEN_SEED_NOT_ENOUGH]: 'GARDEN_SEED_NOT_ENOUGH',
  [ERROR_CODES.GARDEN_NO_EVENT]: 'GARDEN_NO_EVENT',
  [ERROR_CODES.GARDEN_MAX_PLOTS]: 'GARDEN_MAX_PLOTS',
  [ERROR_CODES.GARDEN_NOT_ELDER]: 'GARDEN_NOT_ELDER',
  [ERROR_CODES.GARDEN_ELDER_REQUIREMENT]: 'GARDEN_ELDER_REQUIREMENT',
  [ERROR_CODES.GARDEN_NOT_GRAND_ELDER]: 'GARDEN_NOT_GRAND_ELDER',
  [ERROR_CODES.GARDEN_EXPLORE_LIMIT]: 'GARDEN_EXPLORE_LIMIT',
  [ERROR_CODES.GARDEN_SEED_NOT_MATCH_PLOT]: 'GARDEN_SEED_NOT_MATCH_PLOT',
  [ERROR_CODES.GARDEN_PLOT_WITHERED]: 'GARDEN_PLOT_WITHERED',
  [ERROR_CODES.GARDEN_IN_COMBAT]: 'GARDEN_IN_COMBAT',
  [ERROR_CODES.GARDEN_NOT_IN_COMBAT]: 'GARDEN_NOT_IN_COMBAT',
  [ERROR_CODES.GARDEN_PLOT_HAS_EVENT]: 'GARDEN_PLOT_HAS_EVENT',

  [ERROR_CODES.TAIYI_NOT_MEMBER]: 'TAIYI_NOT_MEMBER',
  [ERROR_CODES.TAIYI_GUIDANCE_COOLDOWN]: 'TAIYI_GUIDANCE_COOLDOWN',
  [ERROR_CODES.TAIYI_INVALID_ELEMENT]: 'TAIYI_INVALID_ELEMENT',
  [ERROR_CODES.TAIYI_CONSCIOUSNESS_NOT_ENOUGH]: 'TAIYI_CONSCIOUSNESS_NOT_ENOUGH',
  [ERROR_CODES.TAIYI_STRIKE_TARGET_NOT_FOUND]: 'TAIYI_STRIKE_TARGET_NOT_FOUND',
  [ERROR_CODES.TAIYI_STRIKE_SELF_NOT_ALLOWED]: 'TAIYI_STRIKE_SELF_NOT_ALLOWED',
  [ERROR_CODES.TAIYI_STRIKE_FAILED]: 'TAIYI_STRIKE_FAILED',
  [ERROR_CODES.TAIYI_BUFF_NOT_ACTIVE]: 'TAIYI_BUFF_NOT_ACTIVE',

  [ERROR_CODES.STAR_NOT_STAR_PALACE]: 'STAR_NOT_STAR_PALACE',
  [ERROR_CODES.STAR_CONSORT_NOT_FOUND]: 'STAR_CONSORT_NOT_FOUND',
  [ERROR_CODES.STAR_GREETING_COOLDOWN]: 'STAR_GREETING_COOLDOWN',
  [ERROR_CODES.STAR_GIFT_NOT_ENOUGH]: 'STAR_GIFT_NOT_ENOUGH',
  [ERROR_CODES.STAR_DISK_NOT_FOUND]: 'STAR_DISK_NOT_FOUND',
  [ERROR_CODES.STAR_DISK_NOT_IDLE]: 'STAR_DISK_NOT_IDLE',
  [ERROR_CODES.STAR_DISK_NOT_READY]: 'STAR_DISK_NOT_READY',
  [ERROR_CODES.STAR_DISK_LOCKED]: 'STAR_DISK_LOCKED',
  [ERROR_CODES.STAR_DISK_NO_EVENT]: 'STAR_DISK_NO_EVENT',
  [ERROR_CODES.STAR_DISK_MAX]: 'STAR_DISK_MAX',
  [ERROR_CODES.STAR_ARRAY_COOLDOWN]: 'STAR_ARRAY_COOLDOWN',
  [ERROR_CODES.STAR_ARRAY_NOT_FOUND]: 'STAR_ARRAY_NOT_FOUND',
  [ERROR_CODES.STAR_ARRAY_ALREADY_JOINED]: 'STAR_ARRAY_ALREADY_JOINED',
  [ERROR_CODES.STAR_ARRAY_FULL]: 'STAR_ARRAY_FULL',
  [ERROR_CODES.STAR_ARRAY_REALM_NOT_MET]: 'STAR_ARRAY_REALM_NOT_MET',
  [ERROR_CODES.STAR_GAZE_COOLDOWN]: 'STAR_GAZE_COOLDOWN',
  [ERROR_CODES.STAR_CHANGE_FATE_COOLDOWN]: 'STAR_CHANGE_FATE_COOLDOWN',
  [ERROR_CODES.STAR_CONSORT_ASSIGNED]: 'STAR_CONSORT_ASSIGNED',
  [ERROR_CODES.STAR_SPIRIT_FEEDBACK_ACTIVE]: 'STAR_SPIRIT_FEEDBACK_ACTIVE',
  [ERROR_CODES.STAR_DISK_HAS_EVENT]: 'STAR_DISK_HAS_EVENT',
  [ERROR_CODES.STAR_INVALID_STAR_TYPE]: 'STAR_INVALID_STAR_TYPE',
  [ERROR_CODES.STAR_ARRAY_EXPIRED]: 'STAR_ARRAY_EXPIRED',
  [ERROR_CODES.STAR_CONSORT_NOT_ASSIGNED]: 'STAR_CONSORT_NOT_ASSIGNED',
  [ERROR_CODES.STAR_CONSORT_STOLEN]: 'STAR_CONSORT_STOLEN',

  [ERROR_CODES.HEISHA_NOT_MEMBER]: 'HEISHA_NOT_MEMBER',
  [ERROR_CODES.HEISHA_SEIZE_COOLDOWN]: 'HEISHA_SEIZE_COOLDOWN',
  [ERROR_CODES.HEISHA_SEIZE_REALM_LOW]: 'HEISHA_SEIZE_REALM_LOW',
  [ERROR_CODES.HEISHA_SEIZE_TARGET_HIGHER]: 'HEISHA_SEIZE_TARGET_HIGHER',
  [ERROR_CODES.HEISHA_SEIZE_TARGET_SELF]: 'HEISHA_SEIZE_TARGET_SELF',
  [ERROR_CODES.HEISHA_SEIZE_TARGET_SAME_SECT]: 'HEISHA_SEIZE_TARGET_SAME_SECT',
  [ERROR_CODES.HEISHA_SEIZE_MAX_PUPPETS]: 'HEISHA_SEIZE_MAX_PUPPETS',
  [ERROR_CODES.HEISHA_SEIZE_ALREADY_ENSLAVED]: 'HEISHA_SEIZE_ALREADY_ENSLAVED',
  [ERROR_CODES.HEISHA_SEIZE_FAILED]: 'HEISHA_SEIZE_FAILED',
  [ERROR_CODES.HEISHA_THEFT_COOLDOWN]: 'HEISHA_THEFT_COOLDOWN',
  [ERROR_CODES.HEISHA_THEFT_REALM_LOW]: 'HEISHA_THEFT_REALM_LOW',
  [ERROR_CODES.HEISHA_THEFT_TARGET_NO_CONSORT]: 'HEISHA_THEFT_TARGET_NO_CONSORT',
  [ERROR_CODES.HEISHA_THEFT_TARGET_NOT_STAR]: 'HEISHA_THEFT_TARGET_NOT_STAR',
  [ERROR_CODES.HEISHA_THEFT_ALREADY_STOLEN]: 'HEISHA_THEFT_ALREADY_STOLEN',
  [ERROR_CODES.HEISHA_BRAINWASH_LIMIT]: 'HEISHA_BRAINWASH_LIMIT',
  [ERROR_CODES.HEISHA_EXTRACT_LIMIT]: 'HEISHA_EXTRACT_LIMIT',
  [ERROR_CODES.HEISHA_NO_STOLEN_CONSORT]: 'HEISHA_NO_STOLEN_CONSORT',
  [ERROR_CODES.HEISHA_PUPPET_NOT_FOUND]: 'HEISHA_PUPPET_NOT_FOUND',
  [ERROR_CODES.HEISHA_ENSLAVED]: 'HEISHA_ENSLAVED',
  [ERROR_CODES.HEISHA_CULTIVATION_BLOCKED]: 'HEISHA_CULTIVATION_BLOCKED',
  [ERROR_CODES.HEISHA_TARGET_NOT_FOUND]: 'HEISHA_TARGET_NOT_FOUND',

  // 血魂幡系统
  [ERROR_CODES.HEISHA_BANNER_NOT_UNLOCKED]: 'HEISHA_BANNER_NOT_UNLOCKED',
  [ERROR_CODES.HEISHA_BANNER_MAX_LEVEL]: 'HEISHA_BANNER_MAX_LEVEL',
  [ERROR_CODES.HEISHA_SACRIFICE_COOLDOWN]: 'HEISHA_SACRIFICE_COOLDOWN',
  [ERROR_CODES.HEISHA_CONVERT_LIMIT]: 'HEISHA_CONVERT_LIMIT',
  [ERROR_CODES.HEISHA_BANNER_LEVEL_LOW]: 'HEISHA_BANNER_LEVEL_LOW',
  [ERROR_CODES.HEISHA_SLOT_NOT_EMPTY]: 'HEISHA_SLOT_NOT_EMPTY',
  [ERROR_CODES.HEISHA_SOUL_NOT_ENOUGH]: 'HEISHA_SOUL_NOT_ENOUGH',
  [ERROR_CODES.HEISHA_SHA_NOT_ENOUGH]: 'HEISHA_SHA_NOT_ENOUGH',
  [ERROR_CODES.HEISHA_SLOT_NOT_REFINING]: 'HEISHA_SLOT_NOT_REFINING',
  [ERROR_CODES.HEISHA_SLOT_NOT_COMPLETE]: 'HEISHA_SLOT_NOT_COMPLETE',
  [ERROR_CODES.HEISHA_FOREST_LIMIT]: 'HEISHA_FOREST_LIMIT',
  [ERROR_CODES.HEISHA_SHADOW_LIMIT]: 'HEISHA_SHADOW_LIMIT',

  // 丹魔之咒错误码
  [ERROR_CODES.CURSE_SELF_TARGET]: 'CURSE_SELF_TARGET',
  [ERROR_CODES.CURSE_NO_ITEM]: 'CURSE_NO_ITEM',
  [ERROR_CODES.CURSE_NOT_ENOUGH_CULTIVATION]: 'CURSE_NOT_ENOUGH_CULTIVATION',
  [ERROR_CODES.CURSE_TARGET_NOT_FOUND]: 'CURSE_TARGET_NOT_FOUND',
  [ERROR_CODES.CURSE_TARGET_ALREADY_CURSED]: 'CURSE_TARGET_ALREADY_CURSED',
  [ERROR_CODES.CURSE_NOT_CASTER]: 'CURSE_NOT_CASTER',
  [ERROR_CODES.CURSE_EXPIRED]: 'CURSE_EXPIRED',
  [ERROR_CODES.CURSE_NOT_CURSED]: 'CURSE_NOT_CURSED',
  [ERROR_CODES.CURSE_NO_ANTIDOTE]: 'CURSE_NO_ANTIDOTE',

  [ERROR_CODES.PVP_LIMIT_REACHED]: 'PVP_LIMIT_REACHED',
  [ERROR_CODES.PVP_TARGET_SELF]: 'PVP_TARGET_SELF',
  [ERROR_CODES.PVP_TARGET_NOT_FOUND]: 'PVP_TARGET_NOT_FOUND',
  [ERROR_CODES.PVP_TARGET_SAME_SECT]: 'PVP_TARGET_SAME_SECT',
  [ERROR_CODES.PVP_REALM_TOO_LOW]: 'PVP_REALM_TOO_LOW',
  [ERROR_CODES.PVP_TARGET_PEACE_MODE]: 'PVP_TARGET_PEACE_MODE',
  [ERROR_CODES.PVP_SOUL_SHATTERED]: 'PVP_SOUL_SHATTERED',

  [ERROR_CODES.LOOT_TARGET_SELF]: 'LOOT_TARGET_SELF',
  [ERROR_CODES.LOOT_TARGET_NOT_FOUND]: 'LOOT_TARGET_NOT_FOUND',
  [ERROR_CODES.LOOT_TARGET_PEACE_MODE]: 'LOOT_TARGET_PEACE_MODE',
  [ERROR_CODES.LOOT_TARGET_NOT_ENOUGH_STONES]: 'LOOT_TARGET_NOT_ENOUGH_STONES',
  [ERROR_CODES.LOOT_COOLDOWN]: 'LOOT_COOLDOWN',
  [ERROR_CODES.LOOT_DAILY_LIMIT]: 'LOOT_DAILY_LIMIT',
  [ERROR_CODES.LOOT_REALM_TOO_LOW]: 'LOOT_REALM_TOO_LOW',

  [ERROR_CODES.WANLING_NOT_MEMBER]: 'WANLING_NOT_MEMBER',
  [ERROR_CODES.WANLING_BEAST_NOT_FOUND]: 'WANLING_BEAST_NOT_FOUND',
  [ERROR_CODES.WANLING_BEAST_MAX_CAPACITY]: 'WANLING_BEAST_MAX_CAPACITY',
  [ERROR_CODES.WANLING_SEARCH_COOLDOWN]: 'WANLING_SEARCH_COOLDOWN',
  [ERROR_CODES.WANLING_SEARCH_DAILY_LIMIT]: 'WANLING_SEARCH_DAILY_LIMIT',
  [ERROR_CODES.WANLING_SEARCH_FAILED]: 'WANLING_SEARCH_FAILED',
  [ERROR_CODES.WANLING_FEED_NO_FOOD]: 'WANLING_FEED_NO_FOOD',
  [ERROR_CODES.WANLING_FEED_SATIETY_FULL]: 'WANLING_FEED_SATIETY_FULL',
  [ERROR_CODES.WANLING_BEAST_NOT_OWNED]: 'WANLING_BEAST_NOT_OWNED',
  [ERROR_CODES.WANLING_BEAST_ALREADY_DEPLOYED]: 'WANLING_BEAST_ALREADY_DEPLOYED',
  [ERROR_CODES.WANLING_BEAST_NOT_DEPLOYED]: 'WANLING_BEAST_NOT_DEPLOYED',
  [ERROR_CODES.WANLING_BEAST_INJURED]: 'WANLING_BEAST_INJURED',
  [ERROR_CODES.WANLING_BEAST_BUSY]: 'WANLING_BEAST_BUSY',
  [ERROR_CODES.WANLING_RAID_COOLDOWN]: 'WANLING_RAID_COOLDOWN',
  [ERROR_CODES.WANLING_RAID_DAILY_LIMIT]: 'WANLING_RAID_DAILY_LIMIT',
  [ERROR_CODES.WANLING_RAID_NO_DEPLOYED]: 'WANLING_RAID_NO_DEPLOYED',
  [ERROR_CODES.WANLING_RAID_TARGET_NOT_FOUND]: 'WANLING_RAID_TARGET_NOT_FOUND',
  [ERROR_CODES.WANLING_RAID_TARGET_NO_GARDEN]: 'WANLING_RAID_TARGET_NO_GARDEN',
  [ERROR_CODES.WANLING_RAID_REALM_LOW]: 'WANLING_RAID_REALM_LOW',
  [ERROR_CODES.WANLING_EVOLVE_LEVEL_NOT_MET]: 'WANLING_EVOLVE_LEVEL_NOT_MET',
  [ERROR_CODES.WANLING_EVOLVE_ITEMS_NOT_ENOUGH]: 'WANLING_EVOLVE_ITEMS_NOT_ENOUGH',
  [ERROR_CODES.WANLING_EVOLVE_NOT_AVAILABLE]: 'WANLING_EVOLVE_NOT_AVAILABLE',
  [ERROR_CODES.WANLING_NAME_INVALID]: 'WANLING_NAME_INVALID',
  [ERROR_CODES.WANLING_NAME_TOO_LONG]: 'WANLING_NAME_TOO_LONG',
  [ERROR_CODES.WANLING_MAX_DEPLOYED]: 'WANLING_MAX_DEPLOYED',
  [ERROR_CODES.WANLING_ABYSS_REALM_LOW]: 'WANLING_ABYSS_REALM_LOW',
  [ERROR_CODES.WANLING_ABYSS_COOLDOWN]: 'WANLING_ABYSS_COOLDOWN',

  [ERROR_CODES.LUOYUN_NOT_MEMBER]: 'LUOYUN_NOT_MEMBER',
  [ERROR_CODES.LUOYUN_WATERING_DAILY_LIMIT]: 'LUOYUN_WATERING_DAILY_LIMIT',
  [ERROR_CODES.LUOYUN_WATERING_EXP_NOT_ENOUGH]: 'LUOYUN_WATERING_EXP_NOT_ENOUGH',
  [ERROR_CODES.LUOYUN_PILL_NOT_FOUND]: 'LUOYUN_PILL_NOT_FOUND',
  [ERROR_CODES.LUOYUN_PILL_NOT_ENOUGH]: 'LUOYUN_PILL_NOT_ENOUGH',
  [ERROR_CODES.LUOYUN_TREE_NOT_HARVESTING]: 'LUOYUN_TREE_NOT_HARVESTING',
  [ERROR_CODES.LUOYUN_TREE_INVADED]: 'LUOYUN_TREE_INVADED',
  [ERROR_CODES.LUOYUN_ALREADY_DEFENDED]: 'LUOYUN_ALREADY_DEFENDED',
  [ERROR_CODES.LUOYUN_NOT_IN_INVASION]: 'LUOYUN_NOT_IN_INVASION',
  [ERROR_CODES.LUOYUN_REWARDS_CLAIMED]: 'LUOYUN_REWARDS_CLAIMED',
  [ERROR_CODES.LUOYUN_NO_CONTRIBUTION]: 'LUOYUN_NO_CONTRIBUTION',
  [ERROR_CODES.LUOYUN_ROOT_ALREADY_UPGRADED]: 'LUOYUN_ROOT_ALREADY_UPGRADED',
  [ERROR_CODES.LUOYUN_LIQUID_NOT_ENOUGH]: 'LUOYUN_LIQUID_NOT_ENOUGH',
  [ERROR_CODES.LUOYUN_INVASION_FAILED]: 'LUOYUN_INVASION_FAILED',
  [ERROR_CODES.LUOYUN_INVALID_PILL_TIER]: 'LUOYUN_INVALID_PILL_TIER',
  [ERROR_CODES.LUOYUN_TREE_NOT_GROWING]: 'LUOYUN_TREE_NOT_GROWING',
  [ERROR_CODES.LUOYUN_ENVIRONMENT_SATISFIED]: 'LUOYUN_ENVIRONMENT_SATISFIED',
  [ERROR_CODES.LUOYUN_CANNOT_SATISFY_ENVIRONMENT]: 'LUOYUN_CANNOT_SATISFY_ENVIRONMENT',

  [ERROR_CODES.YUANYING_NOT_MEMBER]: 'YUANYING_NOT_MEMBER',
  [ERROR_CODES.YUANYING_REALM_TOO_LOW]: 'YUANYING_REALM_TOO_LOW',
  [ERROR_CODES.YUANYING_SOUL_BUSY]: 'YUANYING_SOUL_BUSY',
  [ERROR_CODES.YUANYING_SOUL_IDLE]: 'YUANYING_SOUL_IDLE',
  [ERROR_CODES.YUANYING_PROJECTION_NOT_COMPLETE]: 'YUANYING_PROJECTION_NOT_COMPLETE',
  [ERROR_CODES.YUANYING_CULTIVATION_NOT_AVAILABLE]: 'YUANYING_CULTIVATION_NOT_AVAILABLE',
  [ERROR_CODES.YUANYING_SEEK_TRUTH_COOLDOWN]: 'YUANYING_SEEK_TRUTH_COOLDOWN',
  [ERROR_CODES.YUANYING_SEEK_TRUTH_EXP_NOT_ENOUGH]: 'YUANYING_SEEK_TRUTH_EXP_NOT_ENOUGH',
  [ERROR_CODES.YUANYING_FRAGMENT_INCOMPLETE]: 'YUANYING_FRAGMENT_INCOMPLETE',
  [ERROR_CODES.YUANYING_SWORD_ALREADY_MASTERED]: 'YUANYING_SWORD_ALREADY_MASTERED',
  [ERROR_CODES.YUANYING_MASTER_EXP_NOT_ENOUGH]: 'YUANYING_MASTER_EXP_NOT_ENOUGH',
  [ERROR_CODES.YUANYING_NO_NASCENT_SOUL]: 'YUANYING_NO_NASCENT_SOUL',

  [ERROR_CODES.TOWER_NO_ATTEMPTS]: 'TOWER_NO_ATTEMPTS',
  [ERROR_CODES.TOWER_NOT_IN_TOWER]: 'TOWER_NOT_IN_TOWER',
  [ERROR_CODES.TOWER_MAX_FLOOR]: 'TOWER_MAX_FLOOR',
  [ERROR_CODES.TOWER_FREE_ATTEMPTS_LEFT]: 'TOWER_FREE_ATTEMPTS_LEFT',
  [ERROR_CODES.TOWER_MAX_RESETS]: 'TOWER_MAX_RESETS',
  [ERROR_CODES.TOWER_NOT_ENOUGH_EXP]: 'TOWER_NOT_ENOUGH_EXP',
  [ERROR_CODES.TOWER_IN_TOWER]: 'TOWER_IN_TOWER',

  [ERROR_CODES.MARKET_LISTING_NOT_FOUND]: 'MARKET_LISTING_NOT_FOUND',
  [ERROR_CODES.MARKET_ITEM_NOT_TRADEABLE]: 'MARKET_ITEM_NOT_TRADEABLE',
  [ERROR_CODES.MARKET_ITEM_IS_BOUND]: 'MARKET_ITEM_IS_BOUND',
  [ERROR_CODES.MARKET_NOT_ENOUGH_ITEMS]: 'MARKET_NOT_ENOUGH_ITEMS',
  [ERROR_CODES.MARKET_NOT_ENOUGH_PAYMENT]: 'MARKET_NOT_ENOUGH_PAYMENT',
  [ERROR_CODES.MARKET_CANNOT_BUY_OWN]: 'MARKET_CANNOT_BUY_OWN',
  [ERROR_CODES.MARKET_LISTING_SOLD_OUT]: 'MARKET_LISTING_SOLD_OUT',
  [ERROR_CODES.MARKET_INVALID_QUANTITY]: 'MARKET_INVALID_QUANTITY',
  [ERROR_CODES.MARKET_INVALID_PRICE]: 'MARKET_INVALID_PRICE',
  [ERROR_CODES.MARKET_BUYER_INVENTORY_FULL]: 'MARKET_BUYER_INVENTORY_FULL',
  [ERROR_CODES.MARKET_SELLER_INVENTORY_FULL]: 'MARKET_SELLER_INVENTORY_FULL',
  [ERROR_CODES.MARKET_NOT_LISTING_OWNER]: 'MARKET_NOT_LISTING_OWNER',
  [ERROR_CODES.MARKET_LISTING_CANCELLED]: 'MARKET_LISTING_CANCELLED',
  [ERROR_CODES.MARKET_BUNDLE_MUST_BUY_ALL]: 'MARKET_BUNDLE_MUST_BUY_ALL',

  [ERROR_CODES.CAVE_NOT_OPENED]: 'CAVE_NOT_OPENED',
  [ERROR_CODES.CAVE_ALREADY_OPENED]: 'CAVE_ALREADY_OPENED',
  [ERROR_CODES.CAVE_REALM_NOT_MET]: 'CAVE_REALM_NOT_MET',
  [ERROR_CODES.CAVE_RESOURCES_NOT_ENOUGH]: 'CAVE_RESOURCES_NOT_ENOUGH',
  [ERROR_CODES.CAVE_SPIRIT_VEIN_MAX]: 'CAVE_SPIRIT_VEIN_MAX',
  [ERROR_CODES.CAVE_MEDITATION_MAX]: 'CAVE_MEDITATION_MAX',
  [ERROR_CODES.CAVE_NO_PENDING_ENERGY]: 'CAVE_NO_PENDING_ENERGY',
  [ERROR_CODES.CAVE_NO_PENDING_EXP]: 'CAVE_NO_PENDING_EXP',
  [ERROR_CODES.CAVE_TREASURE_SLOT_INVALID]: 'CAVE_TREASURE_SLOT_INVALID',
  [ERROR_CODES.CAVE_TREASURE_ALREADY_DISPLAYED]: 'CAVE_TREASURE_ALREADY_DISPLAYED',
  [ERROR_CODES.CAVE_TREASURE_SLOT_EMPTY]: 'CAVE_TREASURE_SLOT_EMPTY',
  [ERROR_CODES.CAVE_SCENERY_NOT_UNLOCKED]: 'CAVE_SCENERY_NOT_UNLOCKED',
  [ERROR_CODES.CAVE_NO_VISITOR]: 'CAVE_NO_VISITOR',
  [ERROR_CODES.CAVE_VISITOR_EXPIRED]: 'CAVE_VISITOR_EXPIRED',
  [ERROR_CODES.CAVE_TARGET_NO_CAVE]: 'CAVE_TARGET_NO_CAVE',
  [ERROR_CODES.CAVE_VISIT_SELF]: 'CAVE_VISIT_SELF',
  [ERROR_CODES.CAVE_MESSAGE_EMPTY]: 'CAVE_MESSAGE_EMPTY',
  [ERROR_CODES.CAVE_MESSAGE_TOO_LONG]: 'CAVE_MESSAGE_TOO_LONG',
  [ERROR_CODES.CAVE_MESSAGE_NOT_FOUND]: 'CAVE_MESSAGE_NOT_FOUND',

  [ERROR_CODES.DUNGEON_ALREADY_IN_ROOM]: 'DUNGEON_ALREADY_IN_ROOM',
  [ERROR_CODES.DUNGEON_NOT_IN_ROOM]: 'DUNGEON_NOT_IN_ROOM',
  [ERROR_CODES.DUNGEON_ROOM_NOT_FOUND]: 'DUNGEON_ROOM_NOT_FOUND',
  [ERROR_CODES.DUNGEON_ROOM_FULL]: 'DUNGEON_ROOM_FULL',
  [ERROR_CODES.DUNGEON_NOT_LEADER]: 'DUNGEON_NOT_LEADER',
  [ERROR_CODES.DUNGEON_NOT_ENOUGH_PLAYERS]: 'DUNGEON_NOT_ENOUGH_PLAYERS',
  [ERROR_CODES.DUNGEON_REALM_NOT_MET]: 'DUNGEON_REALM_NOT_MET',
  [ERROR_CODES.DUNGEON_NO_ENTRY_ITEM]: 'DUNGEON_NO_ENTRY_ITEM',
  [ERROR_CODES.DUNGEON_ALREADY_STARTED]: 'DUNGEON_ALREADY_STARTED',
  [ERROR_CODES.DUNGEON_NOT_STARTED]: 'DUNGEON_NOT_STARTED',
  [ERROR_CODES.DUNGEON_INVALID_PATH]: 'DUNGEON_INVALID_PATH',
  [ERROR_CODES.DUNGEON_PATH_ALREADY_SELECTED]: 'DUNGEON_PATH_ALREADY_SELECTED',
  [ERROR_CODES.DUNGEON_STAGE_NOT_READY]: 'DUNGEON_STAGE_NOT_READY',
  [ERROR_CODES.DUNGEON_COMPLETED]: 'DUNGEON_COMPLETED',
  [ERROR_CODES.DUNGEON_FAILED]: 'DUNGEON_FAILED'
}

/**
 * 获取错误类型字符串
 */
export function getErrorType(code: number): string {
  return ERROR_TYPES[code] || 'UNKNOWN_ERROR'
}

/**
 * 根据错误码获取HTTP状态码
 */
export function getHttpStatus(code: number): number {
  if (code === 0) return 200

  // 认证错误
  if (code >= 1001 && code <= 1003) return 401 // 令牌相关
  if (code === ERROR_CODES.AUTH_INVALID_CREDENTIALS) return 401
  if (code === ERROR_CODES.AUTH_USER_NOT_FOUND) return 401
  if (code === ERROR_CODES.AUTH_REFRESH_TOKEN_INVALID) return 401
  if (code === ERROR_CODES.AUTH_ACCOUNT_DELETED) return 403

  // 通用错误
  if (code === ERROR_CODES.FORBIDDEN) return 403
  if (code === ERROR_CODES.NOT_FOUND) return 404
  if (code === ERROR_CODES.INTERNAL_ERROR) return 500

  // 其他业务错误默认400
  return 400
}
